### PR TITLE
feat: Update social media usernames & Add more resources

### PR DESCRIPTION
**Pull request by nayeonshin**
What email address should we use for the website? I just left it as it is (Default address: `your-email@example.com`). Have you thought about tracking users with Google Analytics?

### CODE REVIEW

**Comment by sunithapatel** [comment]
@nayeonshin these changes look good to me so I think we can merge them
@varchanaiyer would you be able to answer the question about the email? It would be nice to have an email to monitor but I don't know how feasible that is.

I was also wondering if it would be at all possible for each track page to have its own social media links on their page as opposed to this one global one. Not sure if you would know how to do that with this theme @nayeonshin?

**Comment by nayeonshin** [comment]
TYSM @sunithapatel! I think this theme has like a universal footer that lives on every page. So on that footer (which is in `_config.yml`, we just leave the WWCode's global social media as they are. But if we wanna achieve that feature, we should probably make a separate section of each track's social media on the tracks' pages. This is the best I can think of as of now. 🤔

**Comment by sunithapatel** [comment]
@nayeonshin yup I was thinking the exact same thing. Feel free to do it if you like, or I might do it myself later (or @varchanaiyer if you want to :)). Thank you!

**Comment by nayeonshin** [comment]
@sunithapatel You're welcome! I'll do that after I wake up this morning. (It's 3 am here. 😉) Have a good day/evening/night.

**Comment by nayeonshin** [comment]
Just came up with the idea that we can probably change the footer links depending on the page. I'm trying to implement this. @sunithapatel @varchanaiyer

**Comment by sunithapatel** [comment]
@nayeonshin Awesome let us know if you need help!!!

**Comment by varchanaiyer** [comment]
Hey @nayeonshin great question, yes I will add it _config.yml. It can be for all the fellows for now; so fellows@womenwhocode.com

**Pull request merged**
